//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petrescu_Mircea_Individuele_opdracht
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImputDataEntities1 : DbContext
    {
        public ImputDataEntities1()
            : base("name=ImputDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestelling> Bestellings { get; set; }
        public virtual DbSet<BestellingProduct> BestellingProducts { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Klant> Klants { get; set; }
        public virtual DbSet<Leverancier> Leveranciers { get; set; }
        public virtual DbSet<Personeelslid> Personeelslids { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
