//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petrescu_Mircea_Individuele_opdracht
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BestellingProducts = new HashSet<BestellingProduct>();
        }
    
        public int ProductID { get; set; }
        public string Naam { get; set; }
        public Nullable<int> Inkoopprijs { get; set; }
        public Nullable<int> Marge { get; set; }
        public Nullable<int> Eenheid { get; set; }
        public Nullable<int> BTW { get; set; }
        public Nullable<int> LeverancierID { get; set; }
        public Nullable<int> CategorieID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestellingProduct> BestellingProducts { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Leverancier Leverancier { get; set; }
    }
}
